Iter5
KretovDmitry/shortener pull request #6
Opened 2024-02-08 16:53 UTC by KretovDmitry

2024-02-13 06:06 UTC, popoffvg requested changes

2024-02-13 06:06 UTC, popoffvg commented on internal/db/db.go
> +	get(key string) (url string, found bool)
Интерфейс не стоит располагать рядом с реализацией, т.к. требования к интерфейсу предъявляет клиент пакета. Исключения составляют пакеты представляющие собой библиотеки

2024-02-13 06:06 UTC, popoffvg commented on internal/db/db.go
> +	set(shortURL, url string)
Интерфейс получился очень сильно зависящим от реализации. Заменить на базу данных окажется проблематично, т.к. при работе с БД могут возникнуть ошибки.

2024-02-13 06:06 UTC, popoffvg commented on internal/db/db.go
> +var m storage = &db{store: make(map[string]string)}
Почти правильная реализация синглтона. Тип синглотона - это интфрейс. 
У такой реализации есть проблемы:
- реализацию синглтона нельзя подменить для тестов (должен быть публичный сеттер, см. zap.ReplaceGlobal)
- более сложную инициализацию синглтона написать при таком дизайне очень сложно

Я бы советовал все же не использовать глобальные переменные.

2024-02-13 06:06 UTC, popoffvg commented on internal/handler/handler.go
> +	body, err := io.ReadAll(r.Body)
Тело обязательно нужно закрывать

2024-02-13 06:06 UTC, popoffvg commented on internal/handler/handler_test.go
> +func testRequest(t *testing.T, ts *httptest.Server, method,
В таких тестах лучше не использовать httptest.Server, а тестировать хендлер изолированно. 

Т.к. тест в пакете хендлер зависит от пакета db. Такого быть не должно. Либо тест интеграционный и он в отдельном пакете, либо стараемся минимизировать зависимости теста.

2024-02-13 06:06 UTC, popoffvg commented on internal/handler/handler_test.go
> +			if resp.StatusCode != http.StatusBadRequest {
Стоило проверку разместить в кейзе как анонимную функцию. Код получился бы более поддерживаемый

2024-02-13 18:12 UTC, KretovDmitry commented on internal/db/db.go
> +	get(key string) (url string, found bool)
Принято, не знал, вынес в отдельный файл пакета db c названием интерфейса storage.go

2024-02-13 18:15 UTC, KretovDmitry commented on internal/db/db.go
> +	set(shortURL, url string)
Добавил в возвращаемые значения ошибку. В данном случае при реализации хранилища в оперативной памяти возникновения ошибки при записи не предвидится. Но для поиска вместо found bool реализовал ошибку ErrURLNotFound.

2024-02-13 18:22 UTC, KretovDmitry commented on internal/db/db.go
> +var m storage = &db{store: make(map[string]string)}
Спасибо за пример zap.ReplaceGlobal, теперь знаю, как делать публичный сеттер.
От глобальной переменной отказался в пользу инициализации хранилища посредством NewInMemoryStore.
Синглтон мною не изучен, соответственно, и трудности при его использовании. Займусь изучением.

2024-02-13 22:21 UTC, KretovDmitry commented on internal/handler/handler_test.go
> +func testRequest(t *testing.T, ts *httptest.Server, method,
Не знал, как это иначе осуществить, не мог mock store подсунуть. Исправил.

2024-02-13 22:23 UTC, KretovDmitry commented on internal/handler/handler_test.go
> +			if resp.StatusCode != http.StatusBadRequest {
Здесь не очень понимаю, как это осуществить. Получается громоздко, вся таблица тестов функциями забита вместо 4 строк.

2024-02-14 19:32 UTC, popoffvg commented on internal/handler/handler_test.go
> +			if resp.StatusCode != http.StatusBadRequest {
Да, увы это так. Есть различные виды тестов. Остановимся на юнит-тестах и интеграционных. 
Возможно, ты знаешь разницу, на всякий случай напомню:
Юнит-тесты пишутся на максимально изолированный участок кода, в идеале функцию, проверяя все взоможные корнер-кейсы. Если решал leetcode или любые другие упражнения по алгоритмам, вот там как раз применяютя юнит-тесты. 
Интеграционные тесты тестируют несколько компонентов приложения в связке и они должны проверять как компоненты работают вместе. В текущем проекте в основном получается писать только их. 

Табличные тесты (которые у тебя реализваны) плохо подходят для интеграционных тестов. Как ты верно заметил получается очень громоздко. Получается выкрутиться анонимнве функциями, когда мы максимально декларативно пытаемся их писать.

2024-02-16 07:10 UTC, merged